import type { ManagedPortfolioItem } from '@sales-automation/neon-state/portfolio-catalog';

const approvedAt = '2026-07-15T00:00:00.000Z';
const approvedBy = 'waseem@codistan.org';

export const approvedStarterPortfolioItems: ManagedPortfolioItem[] = [
  {
    id: 'codistan-software-delivery-capabilities',
    projectName: 'Codistan — Custom Software Delivery Capabilities',
    industry: 'Cross-industry',
    confidentiality: 'public',
    serviceCategories: ['fullstack_web_app', 'nextjs_python_app', 'website_portal', 'enterprise_systems', 'ai_saas_mvp'],
    techStack: ['React', 'Next.js', 'Node.js', 'Python', 'React Native', 'WordPress'],
    problemSolved: 'Organizations need an experienced delivery partner for custom web, mobile, portal and enterprise software initiatives.',
    assetUrls: ['https://codistan.org'],
    tags: ['custom software', 'web application', 'mobile application', 'enterprise system', 'delivery partner'],
    bestProfiles: ['codistan_partner_identity', 'waseem_ai_founder_profile'],
    bestPitchAngle: 'Position Codistan as a structured remote delivery partner with cross-functional engineering and project management capability.',
    approvalStatus: 'approved',
    approvedBy,
    approvedAt,
    approvedProofStatement: 'Codistan provides custom software, web, mobile and enterprise delivery services through a multidisciplinary technology team.',
    approvedOutreachParagraph: 'Codistan can support this requirement with a structured delivery team covering discovery, design, engineering, QA and project management. Our public capabilities overview is available at codistan.org.',
    shareInstructions: 'Share the public Codistan website and the approved capability statement. Add a project-specific case study only after it has been approved in this catalog.',
    doNotDisclose: 'Do not claim named client outcomes, team certifications or delivery metrics unless an approved case-study record explicitly contains them.',
    deliveryModel: 'Remote delivery with project management and optional client-side collaboration.',
    assetHealth: 'available',
    createdAt: approvedAt,
    updatedAt: approvedAt,
  },
  {
    id: 'hilarious-ai-capabilities',
    projectName: 'Hilarious AI — AI Automation and Intelligent Product Capabilities',
    industry: 'Cross-industry',
    confidentiality: 'public',
    serviceCategories: ['ai_automation', 'rag_document_intelligence', 'ai_saas_mvp', 'voice_ai_agent'],
    techStack: ['LLMs', 'RAG', 'Python', 'FastAPI', 'AI agents', 'Voice AI'],
    problemSolved: 'Businesses need practical AI automation, document intelligence, conversational agents and AI-enabled product development.',
    assetUrls: ['https://hilariousai.io'],
    tags: ['ai automation', 'rag', 'document intelligence', 'voice ai', 'ai agent', 'ai saas'],
    bestProfiles: ['waseem_ai_founder_profile', 'us_ai_fullstack_profile'],
    bestPitchAngle: 'Lead with practical automation and measurable workflow improvement without inventing an ROI figure.',
    approvalStatus: 'approved',
    approvedBy,
    approvedAt,
    approvedProofStatement: 'Hilarious AI focuses on AI automation, intelligent agents, RAG and AI-enabled product delivery.',
    approvedOutreachParagraph: 'Hilarious AI can help assess the workflow, define a controlled AI implementation and deliver an initial production-ready solution with human review and measurable acceptance criteria.',
    shareInstructions: 'Share the public Hilarious AI website and use the approved statement. Do not imply a named client deployment unless a separate approved record exists.',
    doNotDisclose: 'Do not invent model performance, savings, client names or production volumes.',
    deliveryModel: 'Remote AI discovery, prototyping, integration and production delivery.',
    assetHealth: 'available',
    createdAt: approvedAt,
    updatedAt: approvedAt,
  },
  {
    id: 'cytas-security-capabilities',
    projectName: 'Cytas — Cybersecurity and Compliance Capabilities',
    industry: 'Technology and regulated organizations',
    confidentiality: 'public',
    serviceCategories: ['cybersecurity_compliance'],
    techStack: ['ISO 27001', 'SOC 2', 'VAPT', 'Cloud Security', 'IAM', 'Microsoft 365 Security'],
    problemSolved: 'Organizations need security assessment, compliance readiness and practical cloud, identity and endpoint security support.',
    assetUrls: ['https://cytas.io'],
    tags: ['cybersecurity', 'compliance', 'iso 27001', 'soc 2', 'vapt', 'iam', 'cloud security'],
    bestProfiles: ['cybersecurity_compliance_profile'],
    bestPitchAngle: 'Position Cytas as a practical security and compliance delivery partner while keeping certification and audit claims evidence-based.',
    approvalStatus: 'approved',
    approvedBy,
    approvedAt,
    approvedProofStatement: 'Cytas provides cybersecurity, compliance, cloud security, IAM and vulnerability-assessment services.',
    approvedOutreachParagraph: 'Cytas can begin with a focused assessment, identify the control and technical gaps, and provide a prioritized implementation plan aligned with the required security or compliance objective.',
    shareInstructions: 'Share the public Cytas website and the approved capability statement. Use named compliance or VAPT examples only after separate approval.',
    doNotDisclose: 'Do not claim formal certification, guaranteed compliance or a passed audit unless the approved evidence explicitly supports it.',
    deliveryModel: 'Remote assessment and implementation support, with onsite work considered separately where required.',
    assetHealth: 'available',
    createdAt: approvedAt,
    updatedAt: approvedAt,
  },
  {
    id: 'motionly-immersive-capabilities',
    projectName: 'Motionly — 3D, Animation and Immersive Delivery Capabilities',
    industry: 'Media, training, products and experiences',
    confidentiality: 'private',
    serviceCategories: ['ar_3d_unity_unreal'],
    techStack: ['Blender', 'Maya', 'Unity', 'Unreal Engine', 'AR', 'VR', '3D Animation'],
    problemSolved: 'Organizations need specialist 3D, animation, AR/VR and real-time interactive production capability.',
    assetUrls: [],
    tags: ['3d animation', 'product animation', 'unity', 'unreal', 'ar', 'vr', 'immersive'],
    bestProfiles: ['ar_3d_animation_profile'],
    bestPitchAngle: 'Use only after an administrator attaches an approved public or anonymized showreel or case-study asset.',
    approvalStatus: 'draft',
    shareInstructions: 'Attach and approve the Motionly profile or showreel before using this item in outbound communication.',
    doNotDisclose: 'Do not send internal profile material or claim named productions until approved.',
    deliveryModel: 'Remote creative production with milestone reviews.',
    assetHealth: 'unchecked',
    createdAt: approvedAt,
    updatedAt: approvedAt,
  },
];
