import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const runtimeSource = readFileSync(new URL('../vercel/workspace-dashboard-runtime.ts', import.meta.url), 'utf8');
const pageSource = readFileSync(new URL('../vercel/workspace-pages.ts', import.meta.url), 'utf8');
const modelSource = readFileSync(new URL('../vercel/workspace-page-model.ts', import.meta.url), 'utf8');
const neonStateSource = readFileSync(new URL('../packages/neon-state/src/index.ts', import.meta.url), 'utf8');
const staticSalesAutomationImport = /import\s+(?!type\b)[\s\S]*?from\s+['"]@sales-automation\//m;

assert.equal(staticSalesAutomationImport.test(runtimeSource), false);
assert.equal(staticSalesAutomationImport.test(pageSource), false);
assert.equal(staticSalesAutomationImport.test(modelSource), false);
assert.equal(runtimeSource.includes("import('@sales-automation/neon-state')"), true);
assert.equal(runtimeSource.includes("import('@sales-automation/prospect-discovery')"), true);
assert.equal(runtimeSource.includes("import('@sales-automation/storage')"), true);
assert.equal(runtimeSource.includes("import('@sales-automation/web/prospect-handler')"), true);
assert.equal(runtimeSource.includes("import('@sales-automation/neon-state/portfolio-catalog')"), false);
assert.equal(runtimeSource.includes('loadNeonDiscoveryRuns'), false);
assert.equal(runtimeSource.includes('loadApprovedPortfolioCatalog'), false);
assert.equal(runtimeSource.includes('persistLeadRecords'), false);
assert.match(runtimeSource, /loadNeonScopedRecordsWithMetrics/);
assert.match(runtimeSource, /new prospectDiscovery\.InMemoryProspectDiscoveryRunStore\(\)/);
assert.match(runtimeSource, /portfolioItems: \[\]/);
assert.match(runtimeSource, /x-prospect-query-count/);
assert.match(runtimeSource, /x-prospect-schema-query-count/);
assert.match(runtimeSource, /x-prospect-support-query-count/);
assert.match(runtimeSource, /x-prospect-schema-cache/);
assert.match(runtimeSource, /x-prospect-runtime-state/);
assert.match(runtimeSource, /PROSPECT_WORKSPACE_TIMING/);
assert.match(runtimeSource, /leadDetailRequested: Boolean\(selectedId\)/);
assert.match(runtimeSource, /prospect_modules/);
assert.match(runtimeSource, /prospect_records/);
assert.match(runtimeSource, /prospect_render/);
assert.match(runtimeSource, /prospect_total/);
assert.match(neonStateSource, /schemaReadiness/);
assert.match(neonStateSource, /ensureNeonSchemaWithMetrics/);
assert.match(neonStateSource, /loadNeonScopedRecordsWithMetrics/);
assert.match(neonStateSource, /SCHEMA_QUERY_COUNT = 5/);
assert.match(neonStateSource, /cacheState: 'cold' \| 'warm'/);
assert.match(neonStateSource, /schemaReadiness\.delete/);
assert.match(neonStateSource, /queryCount: schema\.queryCount \+ 1/);
assert.match(neonStateSource, /dataQueryCount: 1/);
assert.equal(pageSource.includes("from './workspace-page-model.js'"), true);
assert.equal(modelSource.includes('normalizeWorkspacePageQuery'), true);
assert.equal(modelSource.includes('normalizeProspectPageQuery'), false);

console.log('Workspace runtime keeps dynamic boundaries, removes unused GET support loads and exposes scoped Neon query/timing evidence');
